// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjpoivlflcvagnfyogol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqcG9pdmxmbGN2YWduZnlvZ29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzcxMTUsImV4cCI6MjA3NDExMzExNX0.qYJfRxA-NsDRy9NJ45L_HtoPV7hdDpOFSsQzlfcXjYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});